name: Deploy Lambda Container-Image

on:
    push:
        branches: [ main ]  # Trigger deployment only on pushes to main

env: 
    AWS-REGION: eu-north-1
    ECR_URI: ACCOUNT_ID>.dkr.ecr.eu-north-1.amazonaws.com/pqa-repository
    LAMBDA_FUNCTION: pipeline-rf_provider 

jobs:
    deployment:
        runs-on: ubuntu-latest

        permissions:
            id-token: write  # Required for requesting the JWT (OIDC)
            contents: read  #Required for actions/checkout

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6
            
            -   name: Configuration AWS credentials
                uses: aws-actions/configure-aws-credentials@v6
                with:
                    aws-region: ${{env.AWS-REGION}}
                    role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

            -   name: Login to Amazon ECR 
                id: login-ecr-public
                uses: aws-actions/amazon-ecr-login@v2
                with: 
                    registry-type: private

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Build and push image using buildx
                run: | 
                    docker buildx build \
                    --platform linux/amd64 \
                    --provenance=false \
                    --sbom=false \
                    -t ${{ env.ECR_URI }}:latest \
                    -t ${{ env.ECR_URI }}:${{ github.sha }} \
                    --push .

            -   name: Update Lambda Function 
                run: | 
                    aws lambda update-function-code
                    --function-name ${{env.LAMBDA_FUNCTION}}
                    --image-uri ${{ env.ECR_URI }}:${{ github.sha }}